obsidian:
  host: 127.0.0.1
  port: 27123
  secure: false # currently TLS not supported, so make sure it's turned off in the Obsidian Local REST API config
  transaction_folder_path: "Transactions" # path for folder under which to store transaction data (there will be subfolders for year and month)
  category_folder_path: "Spending By Category" # monthly category rollup notes will be stored here
  account_snapshots_folder_path: "AccountSnapshots"

ynab:
  budget: "last-used" # work with the last budget you accessed in the web app; change this to pick a different budget

  # Choose how your YNAB categories map to the categories in your Obsidian vault. If the YNAB category is not found in this mapping,
  # it will be used as-is in your Obsidian vault.
  #
  # category_mapping:
  #   Groceries: "Needs"
  #
  # This assumes your YNAB categories are all uniquely named across all category groups--this is the only behavior supported currently.
  category_mapping: {}

  # These categories will be treated as income, which is analyzed separately from spending.
  income_categories:
    - "Inflow: Ready to Assign"

last_server_knowledge_filename: ".last_server_knowledge.json"
sync_begin_date: None # Or a date like "2025-07-01". If you set this and then update it to be earlier, delete the .last_server_knowledge.json file.
