[project]
name = "ynab-obsidian"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "pyyaml>=6.0.3",
    "requests>=2.32.5",
    "ruff>=0.14.0",
    "ynab>=1.9.0",
]
